POST /api/register HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "hi@mail.com",
    "password": "123456"
}

###
POST /api/login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "hi@mail.com",
    "password": "123456"
}



###
POST /api/links HTTP/1.1
Host: localhost:8888
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhpQG1haWwuY29tIiwiZXhwIjoxNzc1NjQyNjI3LCJ1c2VyX2lkIjozfQ.Ny8JtRjIABX9uWQTd-HUNBBHsGjlB0OpwYRJ84DNUGA

{
  "original_url": "https://github.com/matthewhartstonge/argon2"
}

###
GET /api/links HTTP/1.1
Host: localhost:8888
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhpQG1haWwuY29tIiwiZXhwIjoxNzc1NjQyNjI3LCJ1c2VyX2lkIjozfQ.Ny8JtRjIABX9uWQTd-HUNBBHsGjlB0OpwYRJ84DNUGA

###
DELETE /api/links/6 HTTP/1.1
Host: localhost:8888
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhpQG1haWwuY29tIiwiZXhwIjoxNzc1NjQyNjI3LCJ1c2VyX2lkIjozfQ.Ny8JtRjIABX9uWQTd-HUNBBHsGjlB0OpwYRJ84DNUGA

###
GET  /71ODWt HTTP/1.1
Host: localhost:8888


###
GET  /users HTTP/1.1
Host: localhost:8888
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhpQG1haWwuY29tIiwiZXhwIjoxNzc1NjQyNjI3LCJ1c2VyX2lkIjozfQ.Ny8JtRjIABX9uWQTd-HUNBBHsGjlB0OpwYRJ84DNUGA
