POST /api/register HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "hai@mail.com",
    "password": "123456"
}

###
POST /api/login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "hai@mail.com",
    "password": "123456"
}